### PR TITLE
Allow PHPUnit ^7.0

### PR DESCRIPTION
**Pull request by Slamdunk**

### CODE REVIEW

**Comment by michalbundyra** [comment]
> Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

After changing `composer.json` file `composer.lock` should be updated as well.

**Comment by Slamdunk** [comment]
> After changing composer.json file composer.lock should be updated as well.

Of course, but how?
I mean, we all know the command `composer update --lock` but thisis not the case.
The lock file here is present to test a particular set of depencencies that are neither the lowest nor the latest. The fact is that I don't know how to rebuild it, or putin another way, I don't know the exact envirnoment on how the lock file should be updated into.

**Comment by michalbundyra** [comment]
> Of course, but how?

Basically build should work with any lock file - generated on any env but and builds should check set of different configuration - with different dependencies. I think you can use either 
```console
$ composer update --lock
```
or:
```console
$ composer update nothing
```
and it will just update the hash in `composer.lock`. And it's enough.

**Comment by Slamdunk** [comment]
I repeat what I saidin the previous comment: of course `composer update --lock` updates the lock file hash, but I think it's useless because it doesn't address the purpose of the lock file.

Btw, I've updated it.

**Comment by Ocramius** [comment]
@Slamdunk the only reason to do that is to keep `composer.lock` in sync, even if dependencies are still older than the latest ones.

**Comment by MatyCZ** [comment]
Any ETA to merge?

**Comment by Xerkus** [comment]
@Slamdunk thank you

**Pull request merged**
