### PR TITLE
Added PHPUnit 8 support

### PR DESCRIPTION
**Pull request by michalbundyra**

### CODE REVIEW

**Comment by weierophinney** [comment]
@webimpress Please look at the travis build history and the jobs run for this PR. For the PHP 5/PHPUnit 4 combination, the memory consumption is a full 5x, and for the PHP 7.3/PHPUnit 7 combination, a full 3x. I'm not sure if it's a change in the build system in the past month, or if this patch introduces the slow down, but it either needs to be addressed or explained before we can merge.

**Comment by michalbundyra** [comment]
@weierophinney There was a bug in my implementation. Instead of using `static::class` I've used `__CLASS__` in abstract class, so because of that it was not working properly. Now it's fixed and tests looks promising :) 

Still failing with latest dependencies on PHP 7.2 and 7.3. I'm looking on it.

**Comment by snapshotpl** [comment]
@webimpress looks like ready to deploy, right?

**Comment by michalbundyra** [comment]
@snapshotpl Yes, just someone from maintainers need to find time to release it. I've already pinged @weierophinney

**Comment by snapshotpl** [comment]
@weierophinney :pray:

**Pull request merged**
