### PR TITLE
Support PHPUnit v5

### LINKED ISSUE #3: Allow installation with PHPUnit 5.0
As the test suite pass with PHPUnit 5.0, I think it would be nice to allow this in composer.json

```
"phpunit/PHPUnit": "~4.0|~5.0",
```

or even

```
"phpunit/PHPUnit": ">=4.0",
```

### PR DESCRIPTION
**Pull request by Maks3w**
Fix #3

### CODE REVIEW

**Comment by Maks3w** [comment]
@mwillbanks ping

**Comment by samsonasik** [comment]
@mwillbanks can we have release for it ?

**Comment by mwillbanks** [comment]
Yes, will need to do later today.

**Comment by mwillbanks** [comment]
done.

**Comment by samsonasik** [comment]
@mwillbanks thank you ;)

**Pull request merged**
